sudo: false
language: go
go:
  - 1.8.x
  - master
os:
  - linux
  - osx
install:
  - go get -v -d -t github.com/golang/protobuf/...
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - curl -L https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d $HOME/protoc
  - env
env:
  - PATH=$HOME/protoc/bin:$PATH
matrix:
  allow_failures:
    - go: master
  fast_finish: true
script:
  - make
